name: '[CDM] Build and test'

on:
  workflow_call:
    inputs:
      static-build:
        type: boolean
        required: true
      upload:
        type: boolean
        required: true

env:
  BINARIES: "bin/clang-21 \
             bin/clang \
             bin/opt \
             bin/llc \
             bin/lld \
             bin/ld.lld \
             bin/llvm-ar \
             bin/llvm-as \
             bin/llvm-dis \
             bin/llvm-link \
             bin/llvm-mc \
             bin/llvm-nm \
             bin/llvm-objcopy \
             bin/llvm-objdump \
             bin/llvm-readelf \
             bin/llvm-readobj \
             bin/llvm-size \
             bin/llvm-strings"

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04,  macos-26, windows-2025]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Clone cdm-devkit
        run: |
          git clone --depth 1 https://github.com/cdm-processors/cdm-devkit.git cdm-devkit
      - name: Install `cdm-devkit` package
        run: pip install -e cdm-devkit
      - name: Build cdm-devkit
        run: |
          cd cdm-devkit
          poetry build
      - name: Enable MSVC Dev (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Remove GNU Link (Windows)
        if: runner.os == 'Windows'
        run: |
          rm /usr/bin/link
      - name: Build LLVM (static linking)
        if: inputs.static-build && runner.os == 'Linux'
        run: |
          ./llvm/utils/cdm/build.py --static -j 2 -v
      - name: Build LLVM (dynamic linking)
        if: ${{ !(inputs.static-build && runner.os == 'Linux') }}
        run: |
          ./llvm/utils/cdm/build.py -j 2 -v
      - name: Run end-to-end tests
        if: runner.os != 'Windows' ## TODO: Enable when test system is updated
        run: make -C llvm/test_cdm CLANG=$(realpath llvm/build/bin/clang) test
      - name: Run lit tests (POSIX)
        if: runner.os != 'Windows'
        run: ./llvm/build/bin/llvm-lit ./llvm/test/CodeGen/CDM
      - name: Run lit tests (Windows)
        if: runner.os == 'Windows'
        run: python3 ./llvm/build/bin/llvm-lit.py ./llvm/test/CodeGen/CDM
      - name: Compress artifacts (tarball)
        if: inputs.upload && (runner.os != 'Windows')
        run: |
          OS=${{ runner.os }}
          cd llvm/build && tar -czvf \
            cdm16-llvm-$(echo $OS | tr '[:upper:]' '[:lower:]')-$(uname -m).tar.gz \
              $BINARIES lib/cdm* lib/clang/21/lib/cdm* include/cdm*
      - name: Compress artifacts (zip.. ball?)
        if: inputs.upload && (runner.os == 'Windows')
        run: |
          cd llvm/build
          WIN_BINARIES=$( for file in $BINARIES; do ([ -f "$file".exe ] && echo "$file".exe); done )
          tar -aczf cdm16-llvm-windows-$(uname -m).zip \
            $WIN_BINARIES lib/cdm* lib/clang/21/lib/cdm* include/cdm*
      - name: Upload artifacts
        if: inputs.upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            ./llvm/build/*.tar.gz
            ./llvm/build/*.zip
