name: '[CDM] Build and test'

on:
  workflow_call:
    inputs:
      static-build:
        type: boolean
        required: true
      upload:
        type: boolean
        required: true

env:
  BINARIES: |
    bin/clang-21
    bin/clang
    bin/opt
    bin/llc
    bin/lld
    bin/ld.lld
    bin/llvm-ar
    bin/llvm-as
    bin/llvm-dis
    bin/llvm-link
    bin/llvm-mc
    bin/llvm-nm
    bin/llvm-objcopy
    bin/llvm-objdump
    bin/llvm-readelf
    bin/llvm-readobj
    bin/llvm-size
    bin/llvm-strings
  RESOURCES: |
    lib/cdm
    lib/cdm-unknown-unknown-cocas
    include/cdm

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04,  macos-26, windows-2025]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install cdm-devkit
        run: pip install cdm-devkit==0.2.3
      - name: Enable MSVC Dev (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Remove GNU Link (Windows)
        if: runner.os == 'Windows'
        run: rm /usr/bin/link
      - name: Build LLVM
        run: |
          STATIC=${{ inputs.static-build && runner.os == 'Linux' && '--static' || '' }}
          ./llvm/utils/cdm/build.py -j 2 -v $STATIC
      - name: Run end-to-end tests
        if: runner.os != 'Windows'
        run: make -C llvm/test_cdm CLANG=$(realpath llvm/build/bin/clang) test
      - name: Run lit tests
        run: |
          LLVM_LIT=${{ runner.os == 'Windows' && 'llvm-lit.py' || 'llvm-lit' }}
          python3 ./llvm/build/bin/$LLVM_LIT ./llvm/test/CodeGen/CDM
      - name: Compress artifacts
        if: inputs.upload
        run: |
          OS=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')-$(uname -m)
          OUT_EXT=${{ runner.os == 'Windows' && '.zip' || '.tar.gz' }}
          BIN_EXT=${{ runner.os == 'Windows' && '.exe' || '' }}
          cd llvm/build
          BINARIES=$( for file in $BINARIES; do ([ -f "$file"$BIN_EXT ] && echo "$file"$BIN_EXT); done )
          RESOURCES=$( for file in $RESOURCES; do ([ -e "$file" ] && echo "$file"); done )
          tar -cvaf cdm16-llvm-$OS$OUT_EXT $BINARIES $RESOURCES
      - name: Upload artifacts
        if: inputs.upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            ./llvm/build/cdm16-llvm-*.tar.gz
            ./llvm/build/cdm16-llvm-*.zip
